"""Tests for `app.settings`."""

from __future__ import annotations

from urllib.parse import unquote, urlsplit

import pytest

from app.settings import DEFAULT_DATABASE_URL, DEFAULT_REDIS_URL, Settings

_ENV_VARS = (
    "DATABASE_URL",
    "REDIS_URL",
    "COOKIE_SECURE",
    "ALLOWED_ORIGINS",
    "CACHE_TTL_SECONDS",
    "SESSION_TTL_SECONDS",
    # The component form the ECS task definition injects (INF-05). Cleared
    # here too, or a machine that happens to export one of them would change
    # what "zero environment variables set" means.
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DB_USERNAME",
    "DB_PASSWORD",
    "REDIS_HOST",
    "REDIS_PORT",
    "REDIS_DB",
    "REDIS_TLS",
    "REDIS_AUTH_TOKEN",
)


@pytest.fixture
def clean_env(monkeypatch: pytest.MonkeyPatch) -> None:
    """Removes every setting-related env var so defaults are exercised."""
    for var in _ENV_VARS:
        monkeypatch.delenv(var, raising=False)


def test_settings_load_with_zero_env_vars_set(clean_env: None) -> None:
    """The app must boot with no environment configured at all."""
    settings = Settings.from_env()

    assert settings.database_url
    assert settings.redis_url
    assert settings.cache_ttl_seconds > 0
    assert settings.session_ttl_seconds > 0
    assert settings.allowed_origins


def test_default_cookie_secure_is_false_for_local_http_compose(
    clean_env: None,
) -> None:
    """A plain-HTTP local Compose run must not silently drop cookies."""
    settings = Settings.from_env()

    assert settings.cookie_secure is False


def test_default_allowed_origins_has_no_wildcard(clean_env: None) -> None:
    settings = Settings.from_env()

    assert "*" not in settings.allowed_origins


@pytest.mark.parametrize("raw_value", ["true", "True", "1", "yes", "on"])
def test_cookie_secure_parses_truthy_values(
    monkeypatch: pytest.MonkeyPatch, raw_value: str
) -> None:
    monkeypatch.setenv("COOKIE_SECURE", raw_value)

    settings = Settings.from_env()

    assert settings.cookie_secure is True


@pytest.mark.parametrize("raw_value", ["false", "False", "0", "no", "off", ""])
def test_cookie_secure_parses_falsy_values(
    monkeypatch: pytest.MonkeyPatch, raw_value: str
) -> None:
    monkeypatch.setenv("COOKIE_SECURE", raw_value)

    settings = Settings.from_env()

    assert settings.cookie_secure is False


def test_allowed_origins_parses_comma_separated_list(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv(
        "ALLOWED_ORIGINS", "https://shop.example.com, https://admin.example.com"
    )

    settings = Settings.from_env()

    assert settings.allowed_origins == (
        "https://shop.example.com",
        "https://admin.example.com",
    )


def test_allowed_origins_rejects_wildcard(monkeypatch: pytest.MonkeyPatch) -> None:
    """allow_credentials=True forbids a wildcard origin (ADR-001)."""
    monkeypatch.setenv("ALLOWED_ORIGINS", "*")

    with pytest.raises(ValueError, match="wildcard"):
        Settings.from_env()


def test_allowed_origins_rejects_wildcard_mixed_with_explicit_origins(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setenv("ALLOWED_ORIGINS", "https://shop.example.com,*")

    with pytest.raises(ValueError, match="wildcard"):
        Settings.from_env()


def test_allowed_origins_rejects_empty_string(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("ALLOWED_ORIGINS", "")

    with pytest.raises(ValueError):
        Settings.from_env()


def test_ttl_settings_are_parsed_as_integers(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("CACHE_TTL_SECONDS", "60")
    monkeypatch.setenv("SESSION_TTL_SECONDS", "900")

    settings = Settings.from_env()

    assert settings.cache_ttl_seconds == 60
    assert settings.session_ttl_seconds == 900


def test_settings_is_frozen(clean_env: None) -> None:
    settings = Settings.from_env()

    with pytest.raises(Exception):
        settings.cookie_secure = True  # type: ignore[misc]


# ---------------------------------------------------------------------------
# Composing the store URLs from the parts ECS injects (INF-05)
#
# The password and the Redis AUTH token are generated by CloudFormation into
# Secrets Manager and resolved by ECS as the task starts, so no URL can be
# assembled at synth time. The task definition hands over the components and
# these are the rules for turning them back into a URL.
# ---------------------------------------------------------------------------


@pytest.fixture
def db_components(monkeypatch: pytest.MonkeyPatch) -> None:
    """Sets the `DB_*` variables exactly as the ECS task definition does."""
    monkeypatch.delenv("DATABASE_URL", raising=False)
    monkeypatch.setenv("DB_HOST", "db.abc123.us-east-1.rds.amazonaws.com")
    monkeypatch.setenv("DB_PORT", "5432")
    monkeypatch.setenv("DB_NAME", "qbiq_h")
    monkeypatch.setenv("DB_USERNAME", "appuser")
    monkeypatch.setenv("DB_PASSWORD", "s3cret")


def test_database_url_wins_over_components(
    monkeypatch: pytest.MonkeyPatch, db_components: None
) -> None:
    """Compose and CI both set DATABASE_URL; it must keep taking precedence."""
    monkeypatch.setenv("DATABASE_URL", "postgresql://qbiq:qbiq@localhost:5432/qbiq_h")

    settings = Settings.from_env()

    assert settings.database_url == "postgresql://qbiq:qbiq@localhost:5432/qbiq_h"


def test_database_url_is_composed_from_components(db_components: None) -> None:
    settings = Settings.from_env()

    assert settings.database_url == (
        "postgresql://appuser:s3cret@db.abc123.us-east-1.rds.amazonaws.com:5432/qbiq_h"
    )


def test_database_port_defaults_when_only_the_port_is_absent(
    monkeypatch: pytest.MonkeyPatch, db_components: None
) -> None:
    monkeypatch.delenv("DB_PORT")

    settings = Settings.from_env()

    assert settings.database_url.endswith(":5432/qbiq_h")


def test_database_credentials_with_reserved_characters_round_trip(
    monkeypatch: pytest.MonkeyPatch, db_components: None
) -> None:
    """A generated password is not required to be URL-safe.

    Unescaped, the `@` would end the userinfo early and everything after it
    would be read as the host — a connection failure that names the wrong
    cause. Both consumers of these URLs (`sqlalchemy.engine.make_url` and
    `redis.Redis.from_url`) percent-decode the userinfo, so encoding here is
    what makes the value arrive intact.
    """
    password = "p/a@ss#wo:rd?%"
    monkeypatch.setenv("DB_PASSWORD", password)

    settings = Settings.from_env()
    parsed = urlsplit(settings.database_url)

    assert parsed.hostname == "db.abc123.us-east-1.rds.amazonaws.com"
    assert parsed.port == 5432
    assert parsed.username == "appuser"
    assert unquote(str(parsed.password)) == password
    # The reserved characters really were escaped rather than passed through.
    assert "@" not in settings.database_url.removeprefix("postgresql://").split("@")[0]


def test_database_falls_back_to_the_local_default_without_components(
    clean_env: None,
) -> None:
    settings = Settings.from_env()

    assert settings.database_url == DEFAULT_DATABASE_URL


def test_partially_configured_database_components_raise(
    monkeypatch: pytest.MonkeyPatch, db_components: None
) -> None:
    """Half a configuration must fail loudly, not quietly become localhost.

    Falling back here is the exact defect this composition exists to close:
    the container would boot, answer, and send every query to a database
    that is not there.
    """
    monkeypatch.delenv("DB_PASSWORD")

    with pytest.raises(ValueError, match="DB_PASSWORD"):
        Settings.from_env()


@pytest.fixture
def redis_components(monkeypatch: pytest.MonkeyPatch) -> None:
    """Sets the `REDIS_*` variables exactly as the ECS task definition does."""
    monkeypatch.delenv("REDIS_URL", raising=False)
    monkeypatch.setenv("REDIS_HOST", "cache.abc123.ng.0001.use1.cache.amazonaws.com")
    monkeypatch.setenv("REDIS_PORT", "6379")


def test_redis_url_wins_over_components(
    monkeypatch: pytest.MonkeyPatch, redis_components: None
) -> None:
    monkeypatch.setenv("REDIS_URL", "redis://localhost:6379/0")

    settings = Settings.from_env()

    assert settings.redis_url == "redis://localhost:6379/0"


def test_redis_url_is_composed_from_components(redis_components: None) -> None:
    settings = Settings.from_env()

    assert settings.redis_url == (
        "redis://cache.abc123.ng.0001.use1.cache.amazonaws.com:6379/0"
    )


def test_redis_tls_selects_the_rediss_scheme(
    monkeypatch: pytest.MonkeyPatch, redis_components: None
) -> None:
    """ElastiCache with encryption in transit refuses a plaintext connection."""
    monkeypatch.setenv("REDIS_TLS", "true")

    settings = Settings.from_env()

    assert settings.redis_url.startswith("rediss://")


def test_redis_tls_false_keeps_the_plaintext_scheme(
    monkeypatch: pytest.MonkeyPatch, redis_components: None
) -> None:
    monkeypatch.setenv("REDIS_TLS", "false")

    settings = Settings.from_env()

    assert settings.redis_url.startswith("redis://")


def test_redis_auth_token_is_carried_in_the_password_position(
    monkeypatch: pytest.MonkeyPatch, redis_components: None
) -> None:
    monkeypatch.setenv("REDIS_TLS", "true")
    monkeypatch.setenv("REDIS_AUTH_TOKEN", "token")

    settings = Settings.from_env()
    parsed = urlsplit(settings.redis_url)

    assert parsed.scheme == "rediss"
    assert parsed.username == ""
    assert parsed.password == "token"  # nothing to escape in this one
    assert parsed.hostname == "cache.abc123.ng.0001.use1.cache.amazonaws.com"


def test_redis_auth_token_with_reserved_characters_round_trips(
    monkeypatch: pytest.MonkeyPatch, redis_components: None
) -> None:
    token = "to/ke@n#wi:th?%"
    monkeypatch.setenv("REDIS_AUTH_TOKEN", token)

    settings = Settings.from_env()
    parsed = urlsplit(settings.redis_url)

    assert unquote(str(parsed.password)) == token
    assert parsed.hostname == "cache.abc123.ng.0001.use1.cache.amazonaws.com"
    assert parsed.port == 6379


def test_redis_falls_back_to_the_local_default_without_components(
    clean_env: None,
) -> None:
    settings = Settings.from_env()

    assert settings.redis_url == DEFAULT_REDIS_URL


def test_blank_urls_are_treated_as_unset(
    monkeypatch: pytest.MonkeyPatch, db_components: None, redis_components: None
) -> None:
    """ECS renders an unresolved value as `""` rather than omitting it."""
    monkeypatch.setenv("DATABASE_URL", "")
    monkeypatch.setenv("REDIS_URL", "   ")

    settings = Settings.from_env()

    assert settings.database_url.startswith("postgresql://appuser:")
    assert settings.redis_url.startswith("redis://cache.abc123")
