"""Persistence tier: RDS for PostgreSQL and ElastiCache for Redis.

Both live in the private subnets of the VPC created by the network stack and
are reachable only from the ECS task security group, which is owned by the
backend stack. See `client_targets` below for how that ingress is granted
without creating a stack dependency cycle.
"""

from dataclasses import dataclass

from aws_cdk import CfnOutput, Duration, RemovalPolicy, Stack
from aws_cdk import aws_cloudwatch as cloudwatch
from aws_cdk import aws_ec2 as ec2
from aws_cdk import aws_ecs as ecs
from aws_cdk import aws_elasticache as elasticache
from aws_cdk import aws_rds as rds
from aws_cdk import aws_secretsmanager as secretsmanager
from cdk_nag import NagSuppressions
from constructs import Construct

#: Logical database created inside the instance. It matches the name the local
#: Compose stack uses so that `DATABASE_URL` differs between laptop and
#: production only in host and credentials — the parity argument in ADR-003.
DATABASE_NAME = "qbiq_h"

#: Master user for the application. Its password is generated by CloudFormation
#: into Secrets Manager and is never seen by this code.
DATABASE_USERNAME = "appuser"

DATABASE_PORT = 5432
CACHE_PORT = 6379

#: Characters kept out of the generated password. Every one of them either
#: terminates or re-interprets a component of a `postgresql://user:pass@host/db`
#: URL, and the application reads exactly that URL from `DATABASE_URL`. Keeping
#: them out of the password is cheaper than requiring every consumer to
#: percent-encode correctly, and a 30-character alphabet-restricted password
#: still carries far more entropy than the rest of the system's controls.
PASSWORD_EXCLUDE_CHARACTERS = " %+~`#$&*()|[]{}:;<>?!'/\"\\@,="


@dataclass(frozen=True)
class DataClientTarget:
    """One data-tier security group that ECS tasks need to reach.

    The backend stack turns each of these into an ingress rule **that it owns**,
    so the reference runs backend -> data and never the other way. Adding the
    rule from this side would point data -> backend, and the data stack is
    already referenced by the backend stack for the secrets and endpoints — the
    two together are a `DependencyCycle` at synth time.
    """

    id: str
    security_group: ec2.ISecurityGroup
    port: int
    description: str


class DataStack(Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        env_config: dict,
        vpc: ec2.IVpc,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        is_production = env_config["environment"] == "prod"
        # `PRIVATE_ISOLATED`, not `PRIVATE_WITH_EGRESS`: the VPC has no NAT
        # Gateway (see `network_stack.py` for why), so there is no egress subnet
        # to put these in. Neither Postgres nor Redis ever needed outbound
        # internet, so this is strictly stronger for them — these subnets have no
        # route to an internet gateway at all.
        private_subnets = ec2.SubnetSelection(subnet_type=ec2.SubnetType.PRIVATE_ISOLATED)

        # ------------------------------------------------------------------
        # Security groups
        # ------------------------------------------------------------------
        # Both groups are created with no ingress at all. Every rule that is
        # ever added to them is added by the backend stack, from the ECS task
        # security group, on one port. Nothing in this file can widen them, and
        # in particular nothing here mentions 0.0.0.0/0.
        self.database_security_group = ec2.SecurityGroup(
            self,
            "DatabaseSg",
            vpc=vpc,
            description="RDS Postgres - inbound only from the ECS task security group",
            allow_all_outbound=False,
        )

        self.cache_security_group = ec2.SecurityGroup(
            self,
            "CacheSg",
            vpc=vpc,
            description="ElastiCache Redis - inbound only from the ECS task security group",
            allow_all_outbound=False,
        )

        # ------------------------------------------------------------------
        # RDS for PostgreSQL
        # ------------------------------------------------------------------
        # An explicit subnet group rather than the one DatabaseInstance would
        # generate, so that the "private subnets, 2+ AZs" requirement is a
        # visible property of this stack and not a side effect of a default.
        subnet_group = rds.SubnetGroup(
            self,
            "DatabaseSubnetGroup",
            vpc=vpc,
            vpc_subnets=private_subnets,
            description="Private subnets across every AZ in the VPC",
        )

        self.database = rds.DatabaseInstance(
            self,
            "Database",
            # The major version is pinned; the minor deliberately is not. RDS
            # retires minor versions, and a pinned one eventually stops being
            # orderable: `cdk deploy` failed with "Cannot find version 16.8 for
            # postgres" after the network stack had already been created, and
            # rolled the whole data tier back. Synth cannot catch that, because
            # the CDK enum lists every version AWS has ever published rather
            # than the ones orderable today — VER_16_8 still exists in the enum.
            #
            # VER_16 is the major-only enum member — it renders
            # EngineVersion: "16", which RDS resolves to the current default
            # 16.x at create time (16.13 as of this writing). With
            # auto_minor_version_upgrade below, the instance then tracks minors
            # on its own and this cannot go stale again. Chasing the pin (16.8
            # -> 16.10 -> ...) only defers the same failure.
            #
            # This also explains the synth warning INF-04 recorded as a stale
            # validator false alarm — "DBInstanceClass db.t4g.micro is not valid
            # for EngineVersion 16.8". It was accurate: that combination has
            # zero orderable options.
            #
            # Moving to a new *major* is a separate, deliberate decision — major
            # upgrades are manual and one-way. Check what is offered first:
            #   aws rds describe-orderable-db-instance-options --engine postgres \
            #     --engine-version <v> --db-instance-class <class>
            engine=rds.DatabaseInstanceEngine.postgres(
                version=rds.PostgresEngineVersion.VER_16
            ),
            instance_type=ec2.InstanceType(env_config["db_instance_type"]),
            vpc=vpc,
            vpc_subnets=private_subnets,
            subnet_group=subnet_group,
            security_groups=[self.database_security_group],
            # The password is generated by CloudFormation into a Secrets Manager
            # secret. It exists in no file in this repository, in no environment
            # variable of any build, and in no CloudFormation parameter.
            credentials=rds.Credentials.from_generated_secret(
                DATABASE_USERNAME,
                secret_name=(
                    f"{env_config['environment']}/{env_config['service_name']}/database"
                ),
                exclude_characters=PASSWORD_EXCLUDE_CHARACTERS,
            ),
            database_name=DATABASE_NAME,
            port=DATABASE_PORT,
            publicly_accessible=False,
            storage_encrypted=True,
            storage_type=rds.StorageType.GP3,
            allocated_storage=env_config["db_allocated_storage"],
            max_allocated_storage=env_config["db_max_allocated_storage"],
            backup_retention=Duration.days(env_config["db_backup_retention_days"]),
            multi_az=env_config["db_multi_az"],
            deletion_protection=env_config["db_deletion_protection"],
            auto_minor_version_upgrade=True,
            # Production keeps the instance if the stack is deleted; staging is
            # allowed to go away, but only after a final snapshot.
            removal_policy=RemovalPolicy.RETAIN if is_production else RemovalPolicy.SNAPSHOT,
        )

        #: The generated secret. `DatabaseInstance.secret` is Optional in the
        #: type stubs but is always present with `from_generated_secret`.
        self.database_secret: secretsmanager.ISecret = self.database.secret  # type: ignore[assignment]

        # Automatic rotation used to be configured here, with
        # `add_rotation_single_user`. It has been removed, and this comment is
        # the record of what that costs rather than a silent deletion.
        #
        # The managed rotation Lambda runs inside the VPC and has to call the
        # Secrets Manager API to read the pending secret and mark the rotation
        # complete. That is an internet-facing AWS endpoint. Removing the NAT
        # Gateway (see `network_stack.py`) leaves it no route to reach it, and a
        # Lambda in a VPC never gets a public IP of its own, so there is no
        # public-subnet trick equivalent to the one the ECS tasks use. Left in
        # place it would not fail at deploy — it would fail every 30 days, quietly,
        # marking the secret rotation-failed where nobody is looking.
        #
        # Bringing it back costs one Secrets Manager interface VPC endpoint
        # (~$7.20/month) and one line: pass `endpoint=` to
        # `add_rotation_single_user`. That is the trade, stated so it can be made
        # deliberately.
        #
        # Until then the password is long-lived and rotation is manual: change the
        # secret, then force a new deployment, because ECS resolves `secrets`
        # entries at task start and rotating one does not restart a running task.
        # `docs/runbook.md` carries both commands.

        # ------------------------------------------------------------------
        # ElastiCache for Redis
        # ------------------------------------------------------------------
        # Redis, never Memcached (ADR-003): Memcached has no replication and no
        # failover, so losing a node silently empties every Cart it held.
        # There is no stable L2 construct for ElastiCache, so these are L1.
        cache_subnet_group = elasticache.CfnSubnetGroup(
            self,
            "CacheSubnetGroup",
            description="Private subnets across every AZ in the VPC",
            subnet_ids=vpc.select_subnets(
                subnet_type=ec2.SubnetType.PRIVATE_ISOLATED
            ).subnet_ids,
        )

        # The eviction decision from ADR-003 lives here, in one parameter.
        #
        # Carts and Sessions are application state, not cache, and they carry a
        # TTL like every other key we write — so any `volatile-*` policy is free
        # to evict a live Cart to make room for a product-query cache entry.
        # `noeviction` refuses the write instead, which turns silent data loss
        # into a loud, attributable error. `reserved-memory-percent` keeps a
        # quarter of the node out of the data set so replication and failover
        # buffers cannot be what pushes the instance into that state.
        cache_parameter_group = elasticache.CfnParameterGroup(
            self,
            "CacheParameterGroup",
            cache_parameter_group_family="redis7",
            description="noeviction: Carts are state, not cache (ADR-003)",
            properties={
                "maxmemory-policy": "noeviction",
                "reserved-memory-percent": "25",
            },
        )

        cache_auth_secret = secretsmanager.Secret(
            self,
            "CacheAuthToken",
            secret_name=f"{env_config['environment']}/{env_config['service_name']}/cache",
            description="Redis AUTH token for the ElastiCache replication group",
            generate_secret_string=secretsmanager.SecretStringGenerator(
                generate_string_key="auth_token",
                secret_string_template="{}",
                password_length=64,
                # ElastiCache rejects '/', '"', '@' and spaces in an AUTH token,
                # and the token also has to survive being placed in a
                # `rediss://:token@host` URL. Alphanumeric sidesteps both.
                exclude_punctuation=True,
            ),
        )
        self.cache_auth_secret: secretsmanager.ISecret = cache_auth_secret

        self.cache = elasticache.CfnReplicationGroup(
            self,
            "Cache",
            replication_group_description=(
                f"{env_config['service_name']} sessions, carts and product-query cache"
            ),
            engine="redis",
            engine_version="7.1",
            cache_node_type=env_config["cache_node_type"],
            # One primary plus the configured number of replicas, in a single
            # shard. Automatic failover is the whole reason ADR-003 chose this
            # engine, and it needs at least one replica to fail over to.
            num_cache_clusters=env_config["cache_replicas"] + 1,
            automatic_failover_enabled=True,
            multi_az_enabled=True,
            cache_subnet_group_name=cache_subnet_group.ref,
            cache_parameter_group_name=cache_parameter_group.ref,
            security_group_ids=[self.cache_security_group.security_group_id],
            port=CACHE_PORT,
            at_rest_encryption_enabled=True,
            transit_encryption_enabled=True,
            # Resolved by CloudFormation at deploy time from Secrets Manager;
            # the token itself never appears in the synthesized template.
            auth_token=cache_auth_secret.secret_value_from_json("auth_token").unsafe_unwrap(),
            snapshot_retention_limit=env_config["cache_snapshot_retention_days"],
            auto_minor_version_upgrade=True,
        )
        self.cache.apply_removal_policy(
            RemovalPolicy.RETAIN if is_production else RemovalPolicy.SNAPSHOT
        )

        # `noeviction` only pays off if someone notices the node filling up:
        # the policy converts silent Cart loss into refused writes, and this
        # alarm is what converts refused writes into an action. It deliberately
        # fires well before `maxmemory` is reached, so there is room to resize
        # or to split cache from state (ADR-003) rather than to firefight.
        #
        # No alarm action yet: the SNS topic and its subscriptions belong with
        # the rest of the observability work in CLAUDE.md, alongside the ALB and
        # ECS alarms. Wire this alarm into that topic when it exists.
        cloudwatch.Alarm(
            self,
            "CacheMemoryPressure",
            metric=cloudwatch.Metric(
                namespace="AWS/ElastiCache",
                metric_name="DatabaseMemoryUsagePercentage",
                dimensions_map={"ReplicationGroupId": self.cache.ref},
                statistic="Maximum",
                period=Duration.minutes(5),
            ),
            threshold=75,
            evaluation_periods=3,
            comparison_operator=cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
            treat_missing_data=cloudwatch.TreatMissingData.NOT_BREACHING,
            alarm_description=(
                "ElastiCache is approaching maxmemory. Under the noeviction policy "
                "chosen in ADR-003 the next writes are refused, not evicted: resize the "
                "node or split cache from state before that happens."
            ),
        )

        # ------------------------------------------------------------------
        # What the backend stack consumes
        # ------------------------------------------------------------------
        #: Plain, non-secret connection details for the ECS task definition.
        self.task_environment: dict[str, str] = {
            "DB_HOST": self.database.db_instance_endpoint_address,
            "DB_PORT": self.database.db_instance_endpoint_port,
            "DB_NAME": DATABASE_NAME,
            "REDIS_HOST": self.cache.attr_primary_end_point_address,
            "REDIS_PORT": self.cache.attr_primary_end_point_port,
            # Transit encryption is on, so the client must speak TLS: the scheme
            # is `rediss://`, not `redis://`.
            "REDIS_TLS": "true",
        }

        #: Credentials, as ECS secret references. ECS resolves each of these
        #: from Secrets Manager when the task starts; the values never enter the
        #: task definition, an image layer, or a CloudFormation template.
        self.task_secrets: dict[str, ecs.Secret] = {
            "DB_USERNAME": ecs.Secret.from_secrets_manager(self.database_secret, "username"),
            "DB_PASSWORD": ecs.Secret.from_secrets_manager(self.database_secret, "password"),
            "REDIS_AUTH_TOKEN": ecs.Secret.from_secrets_manager(cache_auth_secret, "auth_token"),
        }

        #: Security groups the ECS task security group must be allowed into. The
        #: backend stack owns the resulting rules — see `DataClientTarget`.
        self.client_targets: tuple[DataClientTarget, ...] = (
            DataClientTarget(
                id="Database",
                security_group=self.database_security_group,
                port=DATABASE_PORT,
                description="ECS tasks to Postgres",
            ),
            DataClientTarget(
                id="Cache",
                security_group=self.cache_security_group,
                port=CACHE_PORT,
                description="ECS tasks to Redis",
            ),
        )

        CfnOutput(self, "DatabaseEndpoint", value=self.database.db_instance_endpoint_address)
        CfnOutput(self, "DatabaseSecretArn", value=self.database_secret.secret_arn)
        CfnOutput(self, "CacheEndpoint", value=self.cache.attr_primary_end_point_address)
        CfnOutput(self, "CacheAuthSecretArn", value=cache_auth_secret.secret_arn)

        # Environment/Service/Owner tags are applied once at the App in app.py and
        # propagate into this stack, so they are deliberately not repeated here.

        self._suppress_nag_findings(is_production=is_production)

    def _suppress_nag_findings(self, is_production: bool) -> None:
        # By path, not by construct. `DatabaseInstance.secret` is the
        # `SecretTargetAttachment`, not the `DatabaseSecret` underneath it, so
        # suppressing on `self.database_secret` annotates the attachment and the
        # finding on the secret itself survives. This is the CfnSecret cdk-nag
        # actually reports.
        NagSuppressions.add_resource_suppressions_by_path(
            self,
            f"/{self.stack_name}/Database/Secret/Resource",
            [
                {
                    "id": "AwsSolutions-SMG4",
                    "reason": (
                        "This secret rotated until the NAT Gateway was removed to cut "
                        "~$32/month from a demo environment. Secrets Manager's managed "
                        "single-user rotation runs as a Lambda inside the VPC and has to "
                        "call the Secrets Manager API to finish; with no NAT there is no "
                        "route to it, and a Lambda in a VPC never gets a public IP, so "
                        "the public-subnet arrangement the ECS tasks use has no "
                        "equivalent here. Leaving it configured would not fail at deploy "
                        "— it would fail every 30 days, silently, which is worse than "
                        "not having it. Restoring it costs one Secrets Manager interface "
                        "VPC endpoint (~$7.20/month) plus `endpoint=` on "
                        "add_rotation_single_user; see the comment where the call used "
                        "to be. Meanwhile the password is generated by CloudFormation, "
                        "exists in no file in this repository, is readable only through "
                        "Secrets Manager, and reaches the task as an ECS `secrets` entry "
                        "resolved at task start. Rotating it by hand is two commands, in "
                        "docs/runbook.md."
                    ),
                }
            ],
        )

        NagSuppressions.add_resource_suppressions(
            self.database,
            [
                {
                    "id": "AwsSolutions-RDS11",
                    "reason": (
                        "The instance listens on 5432. A non-default port is obscurity, "
                        "not a control: the instance has publicly_accessible=False, sits "
                        "in private subnets, and its security group admits exactly one "
                        "source — the ECS task security group — so an attacker who can "
                        "reach the port at all has already crossed every real boundary. "
                        "Against that, 5432 is what the local Compose stack uses, and "
                        "ADR-003 rejected SQLite specifically to keep local and deployed "
                        "behaviour identical; a port that differs per environment is one "
                        "more way for the two to diverge."
                    ),
                }
            ],
        )

        if not is_production:
            # Deliberately conditional: production sets both of these to true in
            # infra/config/prod.py and is therefore checked, not suppressed.
            NagSuppressions.add_resource_suppressions(
                self.database,
                [
                    {
                        "id": "AwsSolutions-RDS3",
                        "reason": (
                            "Staging runs single-AZ. Multi-AZ doubles the instance cost to "
                            "protect a database that holds only a seeded catalogue and can "
                            "be rebuilt by re-running the migration and seed tasks. "
                            "Production sets db_multi_az=True in infra/config/prod.py."
                        ),
                    },
                    {
                        "id": "AwsSolutions-RDS10",
                        "reason": (
                            "Staging is intended to be destroyable, and deletion protection "
                            "would require a console step before every teardown. The "
                            "removal policy is still SNAPSHOT, so a delete leaves a final "
                            "snapshot behind. Production sets db_deletion_protection=True "
                            "in infra/config/prod.py."
                        ),
                    },
                ],
            )

        NagSuppressions.add_resource_suppressions(
            self.cache,
            [
                {
                    "id": "AwsSolutions-AEC5",
                    "reason": (
                        "The replication group listens on 6379, for the same reason the "
                        "database listens on 5432: the only permitted source is the ECS "
                        "task security group, so the port number protects nothing, while "
                        "matching the local Compose stack keeps REDIS_URL identical in "
                        "shape everywhere. Encryption in transit and a Redis AUTH token "
                        "from Secrets Manager are the actual controls here."
                    ),
                }
            ],
        )

        NagSuppressions.add_resource_suppressions(
            self.cache_auth_secret,
            [
                {
                    "id": "AwsSolutions-SMG4",
                    "reason": (
                        "Neither secret in this stack rotates, but for two different "
                        "reasons, and this one is the harder of the two: AWS publishes no "
                        "managed rotation function for an ElastiCache AUTH token at all, "
                        "because changing it is a two-phase ModifyReplicationGroup "
                        "(ROTATE, then SET) against the cluster rather than a write to "
                        "the datastore. So unlike the database secret above — which "
                        "rotated until the NAT Gateway was removed and would work again "
                        "with one VPC endpoint — restoring this needs a custom Lambda "
                        "written from scratch. The token is generated by CloudFormation, "
                        "is never in this repository, and every connection that uses it "
                        "is TLS-encrypted inside the VPC. Write that Lambda if the cache "
                        "ever holds anything that outlives a session."
                    ),
                }
            ],
        )
