"""Runtime configuration loaded from environment variables.

Settings are loaded once, at import time, so they are available as soon as
the application module is imported. Every field has a local-development
default so `uvicorn app.main:app` boots with zero environment variables set.

Two ways to point the app at its stores, in priority order:

1. **A whole URL** — `DATABASE_URL` / `REDIS_URL`. This is what Docker
   Compose and CI set, and it always wins.
2. **The component parts** — `DB_HOST`/`DB_PORT`/`DB_NAME`/`DB_USERNAME`/
   `DB_PASSWORD` and `REDIS_HOST`/`REDIS_PORT`/`REDIS_TLS`/
   `REDIS_AUTH_TOKEN`, from which the URL is composed here.

The second form exists because of ECS. The database password and the Redis
AUTH token are generated by CloudFormation into Secrets Manager and are
resolved by ECS as the task starts, so *nothing at synth time can assemble
a URL out of them* — `infra/stacks/backend_stack.py` can only hand over the
parts, the non-secret ones as plain environment variables and the
credentials as `secrets` entries. Composing the URL is therefore the
application's job, and it happens here rather than in a shell wrapper in
the Dockerfile so that it is covered by `tests/test_settings.py`.

Credentials are percent-encoded on the way in. A generated password
containing `/`, `@`, `#` or `:` otherwise produces a URL that parses
wrongly — `@` in particular ends the userinfo early and the tail of the
password is read as the host, which fails to connect to something that is
not the database rather than failing to authenticate against something
that is.
"""

from __future__ import annotations

import os
from dataclasses import dataclass
from urllib.parse import quote

_TRUE_VALUES = {"1", "true", "yes", "on"}

#: What a laptop with no environment configured at all points at — the ports
#: docker-compose.yml publishes by default.
DEFAULT_DATABASE_URL = "postgresql://qbiq:qbiq@localhost:5432/qbiq_h"
DEFAULT_REDIS_URL = "redis://localhost:6379/0"

_DEFAULT_DB_PORT = "5432"
_DEFAULT_REDIS_PORT = "6379"
_DEFAULT_REDIS_DB = "0"

#: Everything after the scheme is a URL component, so nothing may be left
#: unescaped — `quote`'s default `safe="/"` would happily pass a `/` straight
#: through a password and split the path off in the middle of it.
_NOTHING_IS_SAFE = ""


def _parse_bool(value: str) -> bool:
    """Parses a boolean environment variable value.

    Anything matching one of `_TRUE_VALUES` (case-insensitive) is `True`;
    everything else is `False`.
    """
    return value.strip().lower() in _TRUE_VALUES


def _parse_origins(value: str) -> tuple[str, ...]:
    """Parses a comma-separated list of CORS origins.

    A wildcard origin is rejected: `allow_credentials=True` forbids a
    wildcard origin per ADR-001, since browsers refuse `Access-Control-
    Allow-Origin: *` alongside credentialed requests, which would silently
    break the session cookie.
    """
    origins = tuple(origin.strip() for origin in value.split(",") if origin.strip())
    if not origins:
        raise ValueError("ALLOWED_ORIGINS must contain at least one origin.")
    if "*" in origins:
        raise ValueError(
            "ALLOWED_ORIGINS may not contain a wildcard '*': allow_credentials=True "
            "forbids a wildcard origin (see ADR-001-server-owned-cart.md)."
        )
    return origins


def _env(name: str) -> str | None:
    """Returns a stripped environment variable, treating blank as unset.

    ECS renders an unresolved value as an empty string rather than omitting
    the variable, so `""` has to mean "not configured" or a blank
    `DATABASE_URL` would win over a perfectly good set of components.
    """
    value = os.environ.get(name)
    if value is None:
        return None
    stripped = value.strip()
    return stripped or None


def _database_url() -> str:
    """Returns `DATABASE_URL`, or composes one from the `DB_*` components.

    `DB_HOST` is the marker for component-style configuration. If it is
    absent, nothing was configured and the local default applies. If it is
    present, the remaining components must be too: falling back to
    `localhost` because one variable was forgotten is the exact failure this
    function exists to prevent — the app would boot, `/health` would answer,
    and every query would go to a database that is not there.
    """
    explicit = _env("DATABASE_URL")
    if explicit is not None:
        return explicit

    host = _env("DB_HOST")
    if host is None:
        return DEFAULT_DATABASE_URL

    raw_name = _env("DB_NAME")
    raw_username = _env("DB_USERNAME")
    raw_password = _env("DB_PASSWORD")
    missing = [
        name
        for name, value in (
            ("DB_NAME", raw_name),
            ("DB_USERNAME", raw_username),
            ("DB_PASSWORD", raw_password),
        )
        if value is None
    ]
    if missing:
        raise ValueError(
            "DB_HOST is set, so the database is configured from components, but "
            f"{', '.join(missing)} {'is' if len(missing) == 1 else 'are'} missing. "
            "Set the missing variables, or set DATABASE_URL instead."
        )

    port = _env("DB_PORT") or _DEFAULT_DB_PORT
    username = quote(str(raw_username), safe=_NOTHING_IS_SAFE)
    password = quote(str(raw_password), safe=_NOTHING_IS_SAFE)
    database = quote(str(raw_name), safe=_NOTHING_IS_SAFE)
    return f"postgresql://{username}:{password}@{host}:{port}/{database}"


def _redis_url() -> str:
    """Returns `REDIS_URL`, or composes one from the `REDIS_*` components.

    `REDIS_TLS` selects the scheme: ElastiCache with encryption in transit
    only accepts a TLS connection, and `redis://` against it fails with a
    protocol error rather than anything that names the real cause.
    `REDIS_AUTH_TOKEN` is placed in the password position with an empty
    username, which is how a Redis `requirepass` credential is carried in a
    URL.
    """
    explicit = _env("REDIS_URL")
    if explicit is not None:
        return explicit

    host = _env("REDIS_HOST")
    if host is None:
        return DEFAULT_REDIS_URL

    scheme = "rediss" if _parse_bool(_env("REDIS_TLS") or "") else "redis"
    port = _env("REDIS_PORT") or _DEFAULT_REDIS_PORT
    database = _env("REDIS_DB") or _DEFAULT_REDIS_DB

    token = _env("REDIS_AUTH_TOKEN")
    credentials = ""
    if token is not None:
        credentials = f":{quote(token, safe=_NOTHING_IS_SAFE)}@"

    return f"{scheme}://{credentials}{host}:{port}/{database}"


@dataclass(frozen=True)
class Settings:
    """Immutable, process-wide application configuration."""

    database_url: str
    redis_url: str
    cookie_secure: bool
    allowed_origins: tuple[str, ...]
    cache_ttl_seconds: int
    session_ttl_seconds: int
    log_level: str

    @classmethod
    def from_env(cls) -> "Settings":
        """Builds `Settings` from environment variables with local defaults."""
        return cls(
            database_url=_database_url(),
            redis_url=_redis_url(),
            cookie_secure=_parse_bool(os.environ.get("COOKIE_SECURE", "false")),
            allowed_origins=_parse_origins(
                os.environ.get("ALLOWED_ORIGINS", "http://localhost:5173")
            ),
            cache_ttl_seconds=int(os.environ.get("CACHE_TTL_SECONDS", "300")),
            session_ttl_seconds=int(os.environ.get("SESSION_TTL_SECONDS", "1800")),
            log_level=os.environ.get("LOG_LEVEL", "INFO").upper(),
        )


settings: Settings = Settings.from_env()
